/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shanghaitech_HelloRecognize_CarPlateDetection.h */

#ifndef _Included_com_shanghaitech_HelloRecognize_CarPlateDetection
#define _Included_com_shanghaitech_HelloRecognize_CarPlateDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shanghaitech_HelloRecognize_CarPlateDetection
 * Method:    ImageProc
 * Signature: ([III)Ljava/lang/String;
 */
JNIEXPORT jbyte JNICALL Java_com_shanghaitech_HelloRecognize_CarPlateDetection_ImageProcRead(
		JNIEnv *env, jclass obj, jstring datapath, jstring imgpath);
JNIEXPORT jbyteArray JNICALL Java_com_shanghaitech_HelloRecognize_CarPlateDetection_ImageProc
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
